apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
spec:
  type: LoadBalancer
  ports:
  - port: 7111
  # port target 3111 deployment
    targetPort: 3111
    protocol: TCP
    name: http
  selector:
    app: techtrends    