apiVersion: v1
kind: Service
metadata:
  namespace: sandbox
  name: techtrends
spec:
  #type: LoadBalancer
  type: ClusterIP
  ports:
  - port: 4111
    targetPort: 3111
    protocol: TCP
    name: http
  selector:
    app: techtrends    